### ISSUE TITLE
Number of VMs in HA Cluster (new for vSphere 6.0)

### ISSUE THREAD

**Issue by wodge73** [duncanyb/vsphere-ha-deepdive#1]
**Section:**
Introduction to HA > vSphere 6.0 > What's new in vSphere 6.0?

**Text:**
"Increased VM scale – Cluster limit has grown from X VMs to X VMs per cluster"

**Revision:**
"Increased VM scale – Cluster limit has grown from 4000 VMs to 8000 VMs per cluster"

**Sources:**
[vSphere 5.5](https://www.vmware.com/pdf/vsphere5/r55/vsphere-55-configuration-maximums.pdf):  (p.7)
[vSphere 6.0](https://www.vmware.com/pdf/vsphere6/r60/vsphere-60-configuration-maximums.pdf)  (p.15)

**Comment by duncanyb** [comment]
Thanks, good catch. Just updated!
