### ISSUE TITLE
Chapter 6 contains messed paragraphs

### ISSUE THREAD

**Issue by motlee** [duncanyb/vsphere-ha-deepdive#2]
Thanks for your sharing great knowledge. When I was reading the chapter 6 Restarting Virtual Machines ([http://ha.yellow-bricks.com/restarting_virtual_machines.html](http://ha.yellow-bricks.com/restarting_virtual_machines.html)) I see many sections/paragraphs get duplicated making the chapter contents messed up and confusing. Would you check that?

**Comment by duncanyb** [comment]
Good find, seems like a copy/paste gone wrong. just fixed it. should be a new pdf/html version online in 2-3 minutes

**Comment by motlee** [comment]
Looks fine now. Much appreciated!
